leftnav:
- identifier: 191c427a-2154-4568-b846-1cdfde1176c5
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 9ac6d137-d4f8-4ef1-beb0-46e861d75251
  name: 'Lecture 1: Interactive Proofs and the Sum-Check Protocol'
  pageRef: /pages/lecture-1-interactive-proofs-and-the-sum-check-protocol
  weight: 20
- identifier: de1d02cd-20a3-44ae-a1e6-65aa4faa61df
  name: 'Lecture 2: Doubly Efficient Interactive Proofs'
  pageRef: /pages/lecture-2-doubly-efficient-interactive-proofs
  weight: 30
- identifier: e2701ae6-d386-4440-9080-1d454badfc28
  name: 'Lecture 3: Continuation of the GKR Protocol and Corollaries'
  pageRef: /pages/lecture-3-continuation-of-the-gkr-protocol-and-corollaries
  weight: 40
- identifier: 967658c1-6048-4b28-b9a3-cbd4283789bb
  name: 'Lecture 4: PCP via GKR and Interactive Arguments'
  pageRef: /pages/lecture-4
  weight: 50
- identifier: 5e4778ef-b6c4-4a8f-89e3-ac10e8153d5f
  name: 'Lecture 5: The Kilian-Micali Protocol'
  pageRef: /pages/lecture-5-the-kilian-micali-protocol
  weight: 60
- identifier: 67a08bb8-8845-4955-9dc3-adcdf353d0dd
  name: 'Lecture 6: Fiat-Shamir Paradigm and Zero-Knowledge Proofs'
  pageRef: /pages/lecture-6-fiat-shamir-paradigm-and-zero-knowledge-proofs
  weight: 70
- identifier: 9110715d-58bc-476f-9c74-611fa7844248
  name: 'Lecture 7: Soundness of the Fiat-Shamir Paradigm in the Standard Model '
  pageRef: /pages/lecture-7-soundness-of-the-fiat-shamir-paradigm-in-the-standard-model
  weight: 80
- identifier: 50e5ad1f-11d2-4a7b-a1c7-2e55ded56238
  name: 'Lecture 8: Succinct Non-interactive Arguments for Batch NP (BARGs) from LWE'
  pageRef: /pages/lecture-8-succinct-non-interactive-arguments-for-batch-np-bargs-from-lwe
  weight: 90
- identifier: 5158b18f-daa0-4f68-8801-972fc89d9083
  name: 'Lecture 9: BARGs Implies SNARGs and Connection to Non-signaling PCPs'
  pageRef: /pages/lecture-9-bargs-implies-snargs-and-connection-to-non-signaling-pcps
  weight: 100
- identifier: 155417a8-aa6b-4d09-b407-3ac2c199dbff
  name: Lecture Videos
  pageRef: /video_galleries/lecture-videos
  weight: 110
